### ISSUE TITLE
Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.

### ISSUE THREAD

**Issue by smth** [commodo/glitch-animation-effect#3]
I'm getting this error, seemingly if I embed a page using this script, in an iframe. Visually it works fine, but this error is generated constantly.

**Comment by commodo** [comment]
@smth
can you provide a few more details on this ?
browser ? [ i use Firefox ] and maybe sample html that reproduces

i tried real quick and it did not have any problems
http://rank24.net/~sandu/glitch_test/index4.html

this is also on a more recent source

**Comment by commodo** [comment]
closing this;
if it's still valid please re-open
