### ISSUE TITLE
Uncaught (in promise) Error: Element is not attached to a Document

### ISSUE THREAD

**Issue by HighSoftWare96** [commodo/glitch-animation-effect#4]
I'm not able to run this script for a \<div\>
Here my code:

```
  <script type="text/javascript">
    window.onload = function () {
      var gl1 = Object.create(glitch_exec);
      gl1.start($("#glitch-effect"));
    }
  </script>
```

Where the DOM element is:
```
    <div id="glitch-effect" data-depth=".2" class="title">
      <img src="assets/title@3x.png">
    </div>
```

But it keeps giving me this error:

![image](https://user-images.githubusercontent.com/22793967/60267546-c7996980-98ea-11e9-89a8-cf17c5a7e6cc.png)
Is there something wrong?

**Comment by commodo** [comment]
It's been a while since I used this code.

If you do this, would it work ?
```
  <script type="text/javascript">
    window.onload = function () {
      var gl1 = Object.create(glitch_exec);
      gl1.start(document.getElementById("glitch-effect"));
    }
  </script>
```

IIRC, `$("#glitch-effect")` is usually processed by jQuery or some other framework, and this adds extra behavior.

**Comment by HighSoftWare96** [comment]
Thanks for the reply.. Nope.. neither using document.getElementById...

**Comment by commodo** [comment]
Hmm, then I guess it may have to do with how the rest of the page/JS code is structured.

Maybe try to bind to an event where `"glitch-effect"` div is loaded on the page.
Depending how your code is structured, what you may be seeing is a race condition, where the page loads, but some JS is still doing some processing, and the `"glitch-effect"` div is not loaded/attached to the web-page.
Or, some other JS code is loading and removing or doing some processing on the div.

Can you point me to the entire code?

**Comment by HighSoftWare96** [comment]
Inside the template there are also other Javascript plugins for some other effects (like parallax or particles) but even without that plugins the exception occurs...
```

<html>

<head>
  <link rel="stylesheet" type="text/css" href="css/index.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="./js/html2canvas.min.js"></script>
  <script type="text/javascript" src="./js/glitch-lib.js"></script>
  <script type="text/javascript" src="./js/glitch-execute.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/parallax/3.1.0/parallax.min.js"></script>
  <script src="js/index.js"></script>
  <title>Lotus demo</title>
</head>

<body>
  <div id="scene">
    <div data-depth="0.03" class="background"></div>
    <div id="particles-js"></div>
    <script src="./js/particles.js"></script>
    <div id="glitch-effect" data-depth=".2" class="title">
      <img src="assets/title@3x.png">
    </div>
    <div data-depth=".5" class="images">
      <img data-depth=".1" src="assets/1@3x.png" class="img_1">
      <img data-depth=".2" src="assets/2@3x.png" class="img_2">
      <img data-depth=".2" src="assets/3@3x.png" class="img_3">
      <img data-depth=".4" src="assets/4@3x.png" class="img_4">
      <img data-depth=".1" src="assets/5@3x.png" class="img_5">
    </div>
  </div>
  <script type="text/javascript">
    window.onload = function () {
      var gl1 = Object.create(glitch_exec);
      gl1.start(document.getElementById("glitch-effect"));
    }
  </script>
</body>

</html>
```

**Comment by commodo** [comment]
hmm; 
this seems to work for me [after adapting the code a bit];

I am using [html2canvas.js](https://github.com/commodo/glitch-animation-effect/blob/master/html2canvas.js) from this repo ; and you seem to be using some other `html2canvas.min.js` 
not sure if that makes a difference;

something else that is hard to tell, is what those other JS scripts contain or do
i.e. `js/index.js` & `./js/particles.js`

maybe try removing these 2, and using the `html2canvas.js`, and see from there

**Comment by HighSoftWare96** [comment]
In fact by using your version of html2canvas.js it works now...
Thanks
